// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnzHGYBaFRPb66n_jsk5Csy35KQeIuJEY',
    appId: '1:296558936439:web:42331e114513a930f0e172',
    messagingSenderId: '296558936439',
    projectId: 'brain-voice-379613',
    authDomain: 'brain-voice-379613.firebaseapp.com',
    storageBucket: 'brain-voice-379613.appspot.com',
    measurementId: 'G-R8783MFB8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi6rExuA2aA7u4Ivb8fCvUzvAmx6aGtcM',
    appId: '1:296558936439:android:9415cedd3be35fb8f0e172',
    messagingSenderId: '296558936439',
    projectId: 'brain-voice-379613',
    storageBucket: 'brain-voice-379613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv_wQugTgUoLuKYKEs2cL_um6PPyhSVtI',
    appId: '1:296558936439:ios:ab2998a4e6034104f0e172',
    messagingSenderId: '296558936439',
    projectId: 'brain-voice-379613',
    storageBucket: 'brain-voice-379613.appspot.com',
    iosClientId: '296558936439-3q3n1k2pqerhgrdm672h18ios6b52rr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv_wQugTgUoLuKYKEs2cL_um6PPyhSVtI',
    appId: '1:296558936439:ios:12b324c058d8f81df0e172',
    messagingSenderId: '296558936439',
    projectId: 'brain-voice-379613',
    storageBucket: 'brain-voice-379613.appspot.com',
    iosClientId: '296558936439-l62ojn0apmbvssjlns42dciacm2h29iu.apps.googleusercontent.com',
    iosBundleId: 'com.example.brainVoice.RunnerTests',
  );
}
